### Test that backend is operational

GET http://localhost:3003

### Test adding an author

POST http://localhost:3003/authors HTTP/1.1
Content-Type: application/json

{
    "author_name": "Cheeto Wiz"
}

###

GET http://localhost:3003/authors

### Test adding, updating, and deleting a book

POST http://localhost:3003/books HTTP/1.1
Content-Type: application/json

{
    "isbn": "11111111-111",
    "book_title": "yyyy"
}

###

GET http://localhost:3003/books

###

PUT http://localhost:3003/books HTTP/1.1
Content-Type: application/json

{
    "isbn": "11111111-111",
    "book_title": "NONO"
}

### Test adding, updating, and deleting an author

POST http://localhost:3003/authors HTTP/1.1
Content-Type: application/json

{
    "author_name": "Yeets"
}

###

GET http://localhost:3003/authors

###

PUT http://localhost:3003/authors HTTP/1.1
Content-Type: application/json

{
    "author_ID": "7",
    "author_name": "Yates"
}

###

DELETE http://localhost:3003/authors HTTP/1.1
Content-Type: application/json

{
    "author_ID":"7"
}

### Test connecting Books and Authors
GET http://localhost:3003/books-and-authors

###

GET http://localhost:3003/books

###

GET http://localhost:3003/authors

###

POST http://localhost:3003/books-and-authors
Content-Type: application/json

{
    "isbn": "978-0-123456-47-2",
    "author_ID": "5"
}

###

DELETE http://localhost:3003/books-and-authors HTTP/1.1
Content-Type: application/json

{
    "isbn":"978-0-123456-47-2",
    "author_ID": "5"
}

###
