### Test that backend is operational

GET http://localhost:3003

### Test adding an author

POST http://localhost:3003/authors HTTP/1.1
Content-Type: application/json

{
    "author_name": "Cheeto Wiz"
}

###

GET http://localhost:3003/authors

### Test adding, updating, and deleting a book

POST http://localhost:3003/books HTTP/1.1
Content-Type: application/json

{
    "isbn": "11111111-111",
    "book_title": "yyyy"
}

###

GET http://localhost:3003/books

###

PUT http://localhost:3003/books HTTP/1.1
Content-Type: application/json

{
    "isbn": "11111111-111",
    "book_title": "NONO"
}

###

DELETE http://localhost:3003/books HTTP/1.1
Content-Type: application/json

{
    "isbn":"11111111-111"
}

###
