### Test that backend is operational

GET http://localhost:3003

### Test adding an author

POST http://localhost:3003/authors HTTP/1.1
Content-Type: application/json

{
    "author_name": "Cheeto Wiz"
}

###

GET http://localhost:3003/authors

### Test adding, updating, and deleting a book

POST http://localhost:3003/books HTTP/1.1
Content-Type: application/json

{
    "isbn": "11111111-111",
    "book_title": "yyyy"
}

###

GET http://localhost:3003/books

###

PUT http://localhost:3003/books HTTP/1.1
Content-Type: application/json

{
    "isbn": "11111111-111",
    "book_title": "NONO"
}

### Test adding, updating, and deleting an author

POST http://localhost:3003/authors HTTP/1.1
Content-Type: application/json

{
    "author_name": "Yeets"
}

###

GET http://localhost:3003/authors

###

PUT http://localhost:3003/authors HTTP/1.1
Content-Type: application/json

{
    "author_ID": "7",
    "author_name": "Yates"
}

###

DELETE http://localhost:3003/authors HTTP/1.1
Content-Type: application/json

{
    "author_ID":"7"
}

### Test connecting Books and Authors
GET http://localhost:3003/books-and-authors

###

GET http://localhost:3003/books

###

GET http://localhost:3003/authors

###

POST http://localhost:3003/books-and-authors
Content-Type: application/json

{
    "isbn": "978-0-123456-47-2",
    "author_ID": "5"
}

###

DELETE http://localhost:3003/books-and-authors HTTP/1.1
Content-Type: application/json

{
    "isbn":"978-0-123456-47-2",
    "author_ID": "5"
}

### Test adding, updating, and deleting a resource

GET http://localhost:3003/resources

###

POST http://localhost:3003/resources HTTP/1.1
Content-Type: application/json

{
    "isbn": "978-1-178456-79-4",
    "library_ID": "3",
    "quantity_available": "100"
}

###

PUT http://localhost:3003/resources HTTP/1.1
Content-Type: application/json

{
    "resource_ID": "4",
    "isbn": "978-1-178456-79-4",
    "library_ID": "3",
    "quantity_available": "99",
    "quantity_checked_out": "1"
}

###

DELETE http://localhost:3003/resources HTTP/1.1
Content-Type: application/json

{
    "resource_ID":"5"
}

### Test adding, updating, and deleting a member

GET http://localhost:3003/members

###

POST http://localhost:3003/members HTTP/1.1
Content-Type: application/json

{
    "member_first_name": "Lorn",
    "member_last_name": "For",
    "member_phone": "555-5555"
}

###

PUT http://localhost:3003/members HTTP/1.1
Content-Type: application/json

{
    "member_ID": "4",
    "member_first_name": "Lorne",
    "member_last_name": "Meta",
    "member_phone": "555-5555-6"
}

###

DELETE http://localhost:3003/members HTTP/1.1
Content-Type: application/json

{
    "member_ID":"4"
}

### Test adding, updating, and deleting a library

GET http://localhost:3003/libraries

###

POST http://localhost:3003/libraries HTTP/1.1
Content-Type: application/json

{
    "library_name": "Smithson",
    "library_address": "123 ABC Dr."
}

###

PUT http://localhost:3003/libraries HTTP/1.1
Content-Type: application/json

{
    "library_ID": "4",
    "library_name": "Smithsonian",
    "library_address": "123 XYZ Ave."
}

###

DELETE http://localhost:3003/libraries HTTP/1.1
Content-Type: application/json

{
    "library_ID":"4"
}

### Test adding, updating, and deleting a rental

GET http://localhost:3003/rentals

###

POST http://localhost:3003/rentals HTTP/1.1
Content-Type: application/json

{
    "member_ID": "2",
    "library_ID": "3",
    "rental_date": "2021-02-10"
}

###

PUT http://localhost:3003/rentals HTTP/1.1
Content-Type: application/json

{
    "rental_ID": "3",
    "library_ID": "1",
    "member_ID": "3",
    "rental_date": "2021-02-10"
}

###

DELETE http://localhost:3003/rentals HTTP/1.1
Content-Type: application/json

{
    "rental_ID":"3"
}

### Test adding, updating, and deleting a transfer

GET http://localhost:3003/transfers

###

POST http://localhost:3003/transfers HTTP/1.1
Content-Type: application/json

{
    "source_library_ID": "2",
    "destination_library_ID": "3",
    "transfer_date": "2021-12-10"
}

###

PUT http://localhost:3003/transfers HTTP/1.1
Content-Type: application/json

{
    "transfer_ID": "3",
    "source_library_ID": "1",
    "destination_library_ID": "3",
    "transfer_date": "2021-02-10"
}

###

DELETE http://localhost:3003/transfers HTTP/1.1
Content-Type: application/json

{
    "transfer_ID":"3"
}